In [2]:
import pandas as pd

In [8]:
gdansk = pd.read_csv(r"data\flat-sell_Gdansk.csv", sep='|')
gdynia = pd.read_csv(r"data\flat-sell_Gdynia.csv", sep='|')
sopot = pd.read_csv(r"data\flat-sell_Sopot.csv", sep='|')

In [9]:
gdansk.head()

,Nazwa,Cena,Miasto,Dzielnica,Pow. całkowita,Piętro,Liczba pięter,Liczba sypialni,Rynek,Rok budowy,...,Wysokość wnętrza,Pow. łazienki,Stolarka okienna,Pow. balkonu,Dodatkowe koszty,Cena do negocjacji,Typ nieruchomości,Typ domu,Pow. działki,Lokalizacja garażu
0,Nowa Cena *Prawdziwe zdjęcia*,1 179 000 zł,"Gdańsk,","Letnica,","65,50 m²",13/17,17.0,2.0,Wtórny,2021.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jelitkowo z widokiem na Park Reagana,2 910 000 zł,"Gdańsk,","Jelitkowo,","75,50 m²",2/3,3.0,NaN,Wtórny,2010.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,klimatyczne 3 pokoje z balkonem przy Ołowiance,1 386 000 zł,"Gdańsk,",Śródmieście,77 m²,1/3,3.0,2.0,Wtórny,1921.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2 pokoje Jaśkowa Dolina Cordia,999 000 zł,"Gdańsk,","Wrzeszcz,","55,50 m²",2/3,3.0,1.0,Wtórny,2023.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mieszkanie 2 pokoje Gdańsk Przymorze,539 000 zł,"Gdańsk,","Przymorze,",46 m²,8/10,10.0,NaN,Wtórny,1973.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
sell_data = pd.concat([gdansk, gdynia, sopot])

In [12]:
sell_data.tail()

,Nazwa,Cena,Miasto,Dzielnica,Pow. całkowita,Piętro,Liczba pięter,Liczba sypialni,Rynek,Rok budowy,...,Pow. łazienki,Stolarka okienna,Pow. balkonu,Dodatkowe koszty,Cena do negocjacji,Typ nieruchomości,Typ domu,Pow. działki,Lokalizacja garażu,Kominek
309,Na sprzedaż 3 pokojowe mieszkanie Sopot,650 000 zł,"Sopot,","Przylesie,","46,16 m²",10/10,10.0,NaN,Wtórny,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,Inwestycyjne 3 mieszkania w jednym Sopot koło UG,1 649 000 zł,"Sopot,",Artura Grottgera,"93,10 m²",2/3,3.0,NaN,Wtórny,1950.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,Dwa apaartamenty Sopot,2 290 000 zł,"Sopot,",Władysława Łokietka,74 m²,NaN,3.0,NaN,Wtórny,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,"Sopot Dolny, Sopot Górny, Sopot Wyścigi",1 500 000 zł,"Sopot,","Dolny,",80 m²,NaN,1.0,NaN,Wtórny,1900.0,...,4 m²,NaN,4 m²,NaN,Tak,NaN,NaN,NaN,NaN,NaN
313,Mieszkanie - Sopot,1 880 000 zł,"Sopot,","Dolny,",81 m²,1/2,2.0,NaN,Wtórny,1910.0,...,NaN,NaN,NaN,NaN,Tak,NaN,NaN,NaN,NaN,NaN

In [13]:
sell_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4971 entries, 0 to 313
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Nazwa                       4971 non-null   object
 1   Cena                        4971 non-null   object
 2   Miasto                      4971 non-null   object
 3   Dzielnica                   4917 non-null   object
 4   Pow. całkowita              4971 non-null   object
 5   Piętro                      3637 non-null   object
 6   Liczba pięter               4609 non-null   float64
 7   Liczba sypialni             1745 non-null   float64
 8   Rynek                       4971 non-null   object
 9   Rok budowy                  4386 non-null   float64
 10  Ogrzewanie                  3273 non-null   object
 11  Data dodania                4971 non-null   object
 12  Aktualizacja                4971 non-null   object
 13  Numer ogłoszenia            4971 non-null   object
 14  Liczba odsłon               4971 non-null   object
 15  Liczba Punktów Podbić       4971 non-null   int64
 16  Pow. użytkowa               228 non-null    object
 17  Liczba poziomów mieszkania  1002 non-null   float64
 18  Balkon                      2610 non-null   object
 19  Typ budynku                 3359 non-null   object
 20  Materiał budowlany          1687 non-null   object
 21  Rodzaj umowy                1438 non-null   object
 22  Dostępne od                 1117 non-null   object
 23  Inwestycja                  541 non-null    object
 24  Stan nieruchomości          693 non-null    object
 25  Typ kuchni                  762 non-null    object
 26  Liczba łazienek             602 non-null    float64
 27  łazienka razem z WC         312 non-null    object
 28  Taras                       1140 non-null   object
 29  Pow. ogródka                27 non-null     object
 30  Forma własności             794 non-null    object
 31  Pow. tarasu                 52 non-null     object
 32  Pow. loggii                 35 non-null     object
 33  Stan budynku                309 non-null    object
 34  Wysokość wnętrza            226 non-null    object
 35  Pow. łazienki               91 non-null     object
 36  Stolarka okienna            119 non-null    object
 37  Pow. balkonu                163 non-null    object
 38  Dodatkowe koszty            39 non-null     object
 39  Cena do negocjacji          64 non-null     object
 40  Typ nieruchomości           18 non-null     object
 41  Typ domu                    7 non-null      object
 42  Pow. działki                1 non-null      object
 43  Lokalizacja garażu          2 non-null      object
 44  Kominek                     1 non-null      object
dtypes: float64(5), int64(1), object(39)
memory usage: 1.7+ MB